dist: trusty
sudo: required

#addons:
#  sonarqube:
#    token:
#      secure: SONAR_TOKEN

language: node_js
node_js:
- '6'

notifications:
  email: false

install:
  - npm install

script:
- cd scripts
- . environment_variables_script.sh
- npm test
#- sonar-scanner